# Generated by Django 5.0.6 on 2024-07-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_remove_address_address_alter_paymentdetails_cvv'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='jewelry_images/')),
            ],
        ),
    ]
