# Generated by Django 5.0.6 on 2024-07-10 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_jewelryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelryitem',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
