# Generated by Django 5.0.6 on 2024-08-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_jewelryitem_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelryitem',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
        migrations.AddField(
            model_name='jewelryitem',
            name='colour',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='jewelryitem',
            name='material',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='jewelryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jewelryitem',
            name='ring_size',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='jewelryitem',
            name='seo_meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='jewelryitem',
            name='seo_meta_title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='jewelryitem',
            name='size',
            field=models.CharField(default='M', max_length=50),
        ),
        migrations.AddField(
            model_name='jewelryitem',
            name='sku',
            field=models.CharField(default='SKU0000', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='jewelryitem',
            name='stock_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jewelryitem',
            name='stone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jewelryitem',
            name='stone_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
