# Generated by Django 5.0.6 on 2024-08-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_alter_jewelryitem_category_alter_jewelryitem_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelryitem',
            name='stock_level',
            field=models.IntegerField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default=0),
        ),
    ]
